schema_version = "1.0.0"

id = "fonce_animation_tools"
version = "1.2.9"
name = "Tooling for Animation and Retargetting"
tagline = "Tooling for Animation and Retargetting"
maintainer = "fxn-work@proton.me"
type = "add-on"

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
# network = "Need to sync motion-capture data to server"
# files = "Import/export FBX from/to disk"
# clipboard = "Copy and paste bone transforms"
[build]
paths_exclude_pattern = [
  "builds/*",
  ".git/*",
  ".github/*",
  "__pycache__/*",
  "*.pyc",
  "*.blend1",
  "*.tar.xz",
  "*.zip",
]
