
name: Push to Another Repository
on:
  workflow_call:
    inputs:
      directory:
        required: true
        type: string
    secrets:
      PUSH_TOKEN:
        required: true

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Prepare files
        run: |
          directory = $ {{inputs.directory}}
          mkdir temp_push
          mkdir temp_push/$directory 
          cp -r $directory/* temp_push/$directory/
          cd temp_push
          git init
          git checkout -b main
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated push from source-repo"

      - name: Push to target repo
        env:
          TARGET_REPO: "Fxnarji/extensions"
          TARGET_BRANCH: "main"
          TOKEN: ${{ secrets.PUSH_TOKEN }}
        run: |
          cd temp_push
          git remote add dest https://x-access-token:${TOKEN}@github.com/${TARGET_REPO}.git
          git push --force dest main:${TARGET_BRANCH}
